services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: video-library
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    command: >
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

